/**
 * 稳定错误码 — 所有模块引用这些常量，不散布魔法字符串。
 *
 * §12.4 §16 要求错误码稳定、可机器解析。
 */
export const ErrorCodes = {
  // 歌词校验
  LYRICS_INVALID_MARKDOWN: "LYRICS_INVALID_MARKDOWN",
  LYRICS_TOO_LONG: "LYRICS_TOO_LONG",
  LYRICS_MISSING_SECTION: "LYRICS_MISSING_SECTION",
  STYLE_TOO_LONG: "STYLE_TOO_LONG",
  TITLE_TOO_LONG: "TITLE_TOO_LONG",
  TAGS_INVALID_FORMAT: "TAGS_INVALID_FORMAT",

  // 创作
  SONG_NOT_FOUND: "SONG_NOT_FOUND",
  SONG_NOT_CONFIRMED: "SONG_NOT_CONFIRMED",
  ALBUM_INVALID_MARKDOWN: "ALBUM_INVALID_MARKDOWN",
  ALBUM_TOO_FEW_TRACKS: "ALBUM_TOO_FEW_TRACKS",
  ALBUM_NOT_CONFIRMED: "ALBUM_NOT_CONFIRMED",

  // 提交
  SUBMIT_NOT_AUTHORIZED: "SUBMIT_NOT_AUTHORIZED",
  SUBMIT_NETWORK_ERROR: "SUBMIT_NETWORK_ERROR",
  SUBMIT_ALREADY_IN_PROGRESS: "SUBMIT_ALREADY_IN_PROGRESS",
  SUBMIT_UNKNOWN_STATE: "SUBMIT_UNKNOWN_STATE",

  // 鉴权
  AUTH_EXPIRED: "AUTH_EXPIRED",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",

  // 网络
  SUNO_UNREACHABLE: "SUNO_UNREACHABLE",
  CDN_DOWNLOAD_FAILED: "CDN_DOWNLOAD_FAILED",
  PROXY_UNAVAILABLE: "PROXY_UNAVAILABLE",
  DOCTOR_CHECK_FAILED: "DOCTOR_CHECK_FAILED",

  // 生成
  GENERATION_TIMEOUT: "GENERATION_TIMEOUT",
  GENERATION_FAILED: "GENERATION_FAILED",
  GENERATION_PARTIAL: "GENERATION_PARTIAL",

  // WAV
  WAV_CONVERSION_FAILED: "WAV_CONVERSION_FAILED",
  WAV_CONVERSION_TIMEOUT: "WAV_CONVERSION_TIMEOUT",
  WAV_INVALID_FORMAT: "WAV_INVALID_FORMAT",
  WAV_DOWNLOAD_FAILED: "WAV_DOWNLOAD_FAILED",

  // 文件
  FILE_WRITE_ERROR: "FILE_WRITE_ERROR",
  FILE_NOT_FOUND: "FILE_NOT_FOUND",

  // 页面
  PAGE_STRUCTURE_CHANGED: "PAGE_STRUCTURE_CHANGED",
  PAGE_NAVIGATION_FAILED: "PAGE_NAVIGATION_FAILED",

  // 清单
  MANIFEST_INVALID: "MANIFEST_INVALID",
  MANIFEST_WRITE_ERROR: "MANIFEST_WRITE_ERROR",

  // 通用
  TIMEOUT: "TIMEOUT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
